---
- name: playbook
  hosts: localhost
  tasks:

  - name: task-1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVMPoolConfig
      name: vmpool3
      namespace: sandbox-vmpool-operator-system
    register: vmpool

  - name: debug-1
    debug:
      msg: 
      - 'vmpool: {{ vmpool }}'

  - name: task-2
    set_fact:
      token: '{{ vmpool | json_query(query) }}'
    vars:
      query: "resources[*].spec.token"
  
  - name: debug-2
    debug:
      msg: 
      - 'token: {{ token }}'
