- name: playbook
  hosts: localhost
  vars:
  - provisioning_uri: https://pitc-shared-stage.uc.r.appspot.com/api/v1
  - project_id: stratus-p4d-preview
  - vm_name: vm-kdhali
  - token: ya29.a0AVvZVsqinyptx0Bc6-TEPchW4REQz_oTfDo_eAOnlP7siJImhdtPVXdiFxO88lUUdBkB3z65KQHwWgueHbuPXKMfo05ECXO4i1Evv9QlIdneTcHhgcpqReYO0KFqeXRS2CM4xp2PRDEjzzX4cRZf0jPstwQgl6waCgYKAUQSARASFQGbdwaIDwVyn2EB8UrX6cGmAan7qA0166

  tasks:
  - name: task-1
    uri:
      url: '{{ provisioning_uri }}/projects/{{ project_id }}/vminstances/{{ vm_name }}'
      method: GET
      headers:
        Authorization: "Bearer {{ token }}"
      timeout: 180
      status_code: 200
    register: getvm

  # - name: task-2
  #   set_fact:
  #     getvm2: "{{ getvm | json_query(query) }}"
  #   vars:
  #     query: ".status"

  - name: task-3
    debug:
      msg: 
      - 'getvm: {{ getvm.json.status }}'
