---
- name: task-1
  uri:
    url: '{{ provisioning_uri }}/projects/{{ project_id }}/vminstances/{{ vm_name }}'
    method: GET
    headers:
      Authorization: "Bearer {{ token }}"
    timeout: 180
    status_code: 200
  register: getvm

- name: task-2
  debug:
    msg: 
    - 'getvm_status: {{ getvm.json.status }}'

- name: task-3
  ansible.builtin.copy:
    content: "{{ getvm.json.status }}"
    dest: "/home/stratusadmin/vm.status.log"
