- name: playbook
  hosts: localhost
  tasks:
  - name: Get-VM-CR
    command: kubectl get vmconfig -o json | jq -r '.items[] | select(.spec.host_name=="vmpool-aaj85") | select(.spec.current_vm_state=="present")'
    register: vms

  - name: Debug
    debug:
      msg: "{{ item.metadata.name }}"
    with_items: "{{ item.metadata }}"
