- name: playbook
  hosts: localhost
  tasks:
  - name: Get-VM-CR
    kubernetes.core.k8s_info:
      kind: VMConfig
    register: vms

  - name: Debug
    include_tasks: task-1.yml
    with_items: '{{ vms.resources }}'
