- name: playbook
  hosts: localhost
  tasks:
  - name: Get-VM-CR
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
      metadata:
        ownerReferences:
          name: 

    register: vms


  - name: Debug
    debug:
      msg: "{{ item.metadata.name }} {{ item.metadata.namespace }}"
    with_items: '{{ vms.resources }}'
