- name: playbook
  hosts: localhost
  tasks:
  - name: Get-VM-CR
    shell: 
      "kubectl get vmconfig -o json | jq -r '.items[]'"
    register: vms

  - name: Debug
    debug:
      msg: "{{ item.metadata.name }}"
    with_items: "{{ item.metadata }}"
