- name: playbook
  hosts: localhost
  vars:
  - vmpool: vmpool3
  tasks:
  - name: task-1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
    register: vms

  - name: task-2
    set_fact:
      vms_var: '{{ vms | json_query(query) }}'
    vars:
      query: "resources[?(@.metadata.ownerReferences.name=={{ vmpool }})].spec.vm_name"

  - name: task-3
    debug:
      msg:
      - 'vms_var: {{ vms_var }}'
