- name: playbook
  hosts: localhost
  tasks:
  - name: task-1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
    register: vms

  - name: task-2
    set_fact:
      current_num_hot_free_vms_var: '{{ vms | json_query(query) }}'
    vars:
      query: "resources[*]"

  - name: task-3
    debug:
      msg: 
      - 'current_num_hot_free_vms: {{ current_num_hot_free_vms_var }}'
