- name: playbook
  hosts: localhost
  tasks:
  - name: task1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
    register: vms
  
  - name: task2
    set_fact:
      vms_list: "{{ vms | json_query(query) }}"
    vars:
      query: "resources[?(@.spec.host_name=='vmpool2-bnd15' && @.spec.current_vm_state=='present')]"

  - name: task3
    debug:
      msg: "{{ vms_list }}"
