- name: playbook
  hosts: localhost
  tasks:
  - name: PtsVMPoolConfig-test-1-task1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
      field_selectors:
      - spec.current_vm_status==running
    register: vms

  - name: PtsVMPoolConfig-test-1-task2
    debug:
      msg:
      - msg="{{ vms | jq -r '.items[] | select(.spec.host_name=="vmpool2-bnd15") }}"
