- name: playbook
  hosts: localhost
  tasks:
  - name: PtsVMPoolConfig-test-1-task1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
    register: vms
  
  - name: FILTER FOR POD NAME AND STATE
    set_fact:
      filtered_result: "{{ vms | json_query(query) }}"
    vars:
      query: "[].{spec.current_vm_state}"

  - name: DISPLAY FILTERED RESULTS
    debug:
      msg: "{{ filtered_result }}"
