- name: Master-playbook
  hosts: localhost
  vars:
  - current_num_cold_free_vms_var: 0
  - desired_num_cold_free_vms: 5
  - current_num_hot_free_vms_var: 10
  - desired_num_hot_free_vms: 5  

  tasks:
  - name: master-task1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
    register: vms
 
  - name: master-task2
    set_fact:
      free_hot_vms: "{{ vms | json_query(query) }}"
    vars:
      query: "resources[?(@.spec.current_vm_state=='present')].spec.host_name"

  - name: master-task3
    include_tasks: sub-task-1.yml
    with_items: '{{ free_hot_vms[0] }}'
    when: current_num_cold_free_vms_var | int < desired_num_cold_free_vms | int and
          current_num_hot_free_vms_var | int > desired_num_hot_free_vms | int