- name: playbook
  hosts: localhost
  tasks:
  - name: task-1
    kubernetes.core.k8s_info:
      api_version: vmpool-operator.slb.com/v1
      kind: PtsVmControl
      namespace: sandbox-vmpool-operator-system
    register: vms

  - name: task-2
    set_fact:
      vms: "{{ vms | json_query(query) }}"
    vars:
      query: "resources[*].spec.vm_name"

  - name: task-2
    debug:
      msg: 
      - 'count: {{ vms.count | int }}'
