- name: playbook
  hosts: localhost
  tasks:
  - name: PtsVMPoolConfig-test-1-task1
    command: kubectl get PtsVMControl -o jsonpath='{.items[?(@.spec.current_vm_state=="present")]}'
    register: vms

  # - name: FILTER FOR POD NAME AND STATE
  #   set_fact:
  #     vms_list: "{{ vms | json_query(query) }}"
  #   vars:
  #     query: "resources[].spec"

  - name: FILTER FOR POD NAME AND STATE
    debug:
      msg: "{{ vms }}"
