---
- name: playbook
  hosts: localhost
  vars:
  - provisioning_uri: https://pitc-shared-stage.uc.r.appspot.com/api/v1
  - project_id: stratus-p4d-preview
  - vm_name: vm-kdhali
  - token: ya29.a0AVvZVsp4Xyy-ZvnAU01afwSD23U0wgGh4_pPpbxCo_MyudQNSLYJleUGh-uyilsa0EVXAfKjrXPmOwk0ICTF7SIxYvN5rxqtJR7xTXGTFeLbxVnjvNiFS-6uAM0UGBLIoMdlu0j_lFZ-yf3mA6ZyNXQ1azncPZEaCgYKAZISARASFQGbdwaIkLjNu2PUaayZ-Wfgi7dLTw0166

  tasks:
  - name: task-1
    uri:
      url: '{{ provisioning_uri }}/projects/{{ project_id }}/vminstances/{{ vm_name }}'
      method: GET
      headers:
        Authorization: "Bearer {{ token }}"
      timeout: 180
      failed_when: false
    register: getvm
  
  - name: task-3
    debug:
      msg: 
      - 'status: {{ getvm.json.status }}'

  - name: task-3
    debug:
      msg: 
      - 'getvm: {{ getvm.json }}'